from .bond_nodes import (
    BondGlobalMetadataSettings,
    PromptJSONSelector,
    BatchIntPick,
    BatchStringPick,
    BondPromptArrayIterator,
    CartesianIndexDriverImg,
    CartesianIndexDriverImgPrmpt,
    RangeStepper,
    BondSwitch2to1,
    BondSwitch1to2,
    BondLoadImage,
    BondLoadVideo,
    LoadImageFromPath,
    LoadVideoFromPath,
    BondBatchImageLoader,
    BondShowText,
    BondReadMetadata,
    BondStripMetadata,
    BondSaveWithCustomMetadata,
    BondSaveVideoWithMetadata,
)

NODE_CLASS_MAPPINGS = {
    "PromptJSONSelector":           PromptJSONSelector,
    "BatchIntPick":                 BatchIntPick,
    "BatchStringPick":              BatchStringPick,
    "BondPromptArrayIterator":      BondPromptArrayIterator,
    "CartesianIndexDriverImg":      CartesianIndexDriverImg,
    "CartesianIndexDriverImgPrmpt": CartesianIndexDriverImgPrmpt,
    "RangeStepper":                 RangeStepper,
    "BondSwitch2to1":               BondSwitch2to1,
    "BondSwitch1to2":               BondSwitch1to2,
    "BondLoadImage":                BondLoadImage,
    "BondLoadImageFromPath":        LoadImageFromPath,
    "BondLoadVideoFromPath":        LoadVideoFromPath,
    "BondLoadVideo":                BondLoadVideo,
    "BondBatchImageLoader":         BondBatchImageLoader,
    "BondShowText":                 BondShowText,
    "BondReadMetadata":             BondReadMetadata,
    "BondStripMetadata":            BondStripMetadata,
    "BondGlobalMetadataSettings":   BondGlobalMetadataSettings,
    "BondSaveWithCustomMetadata":   BondSaveWithCustomMetadata,
    "BondSaveVideoWithMetadata":    BondSaveVideoWithMetadata,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "PromptJSONSelector":           "Bond: Prompt JSON/TXT Selector",
    "BatchIntPick":                 "Bond: Batch → Int Pick",
    "BatchStringPick":              "Bond: Batch → String Pick",
    "BondPromptArrayIterator":      "Bond: Prompt Array Iterator",
    "CartesianIndexDriverImg":      "Bond: Cartesian Index Driver (Image)",
    "CartesianIndexDriverImgPrmpt": "Bond: Cartesian Index Driver (Img + Prompt)",
    "RangeStepper":                 "Bond: Range Stepper",
    "BondSwitch2to1":               "Bond: Switch 2→1 🔀",
    "BondSwitch1to2":               "Bond: Switch 1→2 🔀",
    "BondLoadImage":                "Bond: Load Image 🖼️",
    "BondLoadImageFromPath":        "Bond: Load Image From Path",
    "BondLoadVideoFromPath":        "Bond: Load Video From Path",
    "BondLoadVideo":                "Bond: Load Video 🎬",
    "BondBatchImageLoader":         "Bond: Batch Image Loader",
    "BondShowText":                 "Bond: Show Text 📝",
    "BondReadMetadata":             "Bond: Read Metadata 🔍",
    "BondStripMetadata":            "Bond: Strip Metadata 🧹",
    "BondGlobalMetadataSettings":   "Bond: Global Metadata Settings 🌐",
    "BondSaveWithCustomMetadata":   "Bond: Save Image With Custom Metadata ✨",
    "BondSaveVideoWithMetadata":    "Bond: Save Video With Custom Metadata 🎬",
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

WEB_DIRECTORY = "js"
